export const SET_PROJECT = "SET_PROJECT";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE";

export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";
export const GET_ALL_PROJECTS_FAILURE = "GET_ALL_PROJECTS_FAILURE";

export const SET_ALL_PROJECTS = "SET_ALL_PROJECTS";
export const SET_ALL_PROJECTS_SUCCESS = "SET_ALL_PROJECTS_SUCCESS";
export const SET_ALL_PROJECTS_FAILURE = "SET_ALL_PROJECTS_FAILURE";

export const SET_PROJECT_TREE = "SET_PROJECT_TREE";
