export const SET_COMPONENT = 'SET_COMPONENT';
export const SET_ALL_COMPONENTS = 'SET_ALL_COMPONENTS';
export const GET_COMPONENT = 'GET_COMPONENT';
export const GET_ALL_COMPONENTS = 'GET_ALL_COMPONENTS';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const FILTER_COMPONENTS = 'FILTER_COMPONENTS';
export const SET_COMPONENT_TREE = 'SET_COMPONENT_TREE';
