export const GENERATE_CODE = "GENERATE_CODE";
export const GENERATE_CODE_SUCCESS = "GENERATE_CODE_SUCCESS";
export const GENERATE_CODE_FAIL = "GENERATE_CODE_FAIL";
export const INIT_PROJECT = "INIT_PROJECT";
