export const SET_PROVIDER = 'SET_PROVIDER';
export const SET_ALL_PROVIDERS = 'SET_ALL_PROVIDERS';
export const GET_PROVIDER = 'GET_PROVIDER';
export const GET_ALL_PROVIDERS = 'GET_ALL_PROVIDERS';
export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const FILTER_PROVIDERS = 'FILTER_PROVIDERS';
