export const PRETTIFY_CODE = "PRETTIFY_CODE";
export const PRETTIFY_CODE_SUCCESS = "PRETTIFY_CODE_SUCCESS";
export const PRETTIFY_CODE_FAIL = "PRETTIFY_CODE_FAIL";
export const EXPORT_MODULES = 'EXPORT_MODULES';