export const SET_TEMPLATE = "SET_TEMPLATE";
export const SET_TEMPLATE_SUCCESS = "SET_TEMPLATE_SUCCESS";
export const SET_TEMPLATE_FAILURE = "SET_TEMPLATE_FAILURE";

export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";
export const DELETE_TEMPLATE_FAILURE = "DELETE_TEMPLATE_FAILURE";

export const GET_TEMPLATE = "GET_TEMPLATE";
export const GET_TEMPLATE_SUCCESS = "GET_TEMPLATE_SUCCESS";
export const GET_TEMPLATE_FAILURE = "GET_TEMPLATE_FAILURE";

export const GET_ALL_TEMPLATES = "GET_ALL_TEMPLATES";
export const GET_ALL_TEMPLATES_SUCCESS = "GET_ALL_TEMPLATES_SUCCESS";
export const GET_ALL_TEMPLATES_FAILURE = "GET_ALL_TEMPLATES_FAILURE";

export const SET_ALL_TEMPLATES = "SET_ALL_TEMPLATES";
export const SET_ALL_TEMPLATES_SUCCESS = "SET_ALL_TEMPLATES_SUCCESS";
export const SET_ALL_TEMPLATES_FAILURE = "SET_ALL_TEMPLATES_FAILURE";

export const SET_TEMPLATE_TREE = "SET_TEMPLATE_TREE";
export const SET_CURRENT_TEMPLATE = 'SET_CURRENT_TEMPLATE';
