export const PRETTIFY_CODE = "PRETTIFY_CODE";
export const PRETTIFY_CODE_SUCCESS = "PRETTIFY_CODE_SUCCESS";
export const PRETTIFY_CODE_FAIL = "PRETTIFY_CODE_FAIL";
export const EXPORT_MODULES = 'EXPORT_MODULES';

export const AUTHENTICATE = 'AUTHENTICATE';
export const REGISTER = 'REGISTER';

export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';

export const GET_COLLECTION = 'GET_COLLECTION';